apiVersion: v1
kind: Service
metadata:
  name: hello-app
  labels:
    app: hello-app

spec:
  type: {{ .Values.service.type }}

  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
      protocol: TCP
      name: http

  selector:
    app: hello-app